language: csharp
solution: build/CoiniumServ.sln

os:
  - osx
  - linux
  
mono:
  - latest
  - 4.8.0
  - 4.6.2
  - 4.4.2
  - 4.2.3
  - 4.0.5
  
script:
- xbuild build/CoiniumServ.sln /p:Configuration="Debug"
- xbuild build/CoiniumServ.sln /p:Configuration="Release"
- mono contrib/xunit/xunit.console.clr4.x86.exe src/Tests/bin/Debug/CoiniumServ.Tests.dll
- mono contrib/xunit/xunit.console.clr4.x86.exe src/Tests/bin/Release/CoiniumServ.Tests.dll

notifications:
  email: false
